[versions]
composeDesktop = "1.2.0-alpha01-dev750"
coroutines = "1.6.0"
ideaGradlePlugin = "1.7.0"
jna = "5.10.0"
kotlin = "1.7.10"
kotlinxSerialization = "1.3.1"
skiko = "0.7.26"

[libraries]
compose-components-splitpane = { module = "org.jetbrains.compose.components:components-splitpane", version.ref = "composeDesktop" }
jna = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
composeDesktop = { id = "org.jetbrains.compose", version.ref = "composeDesktop" }
ideaGradlePlugin = { id = "org.jetbrains.intellij", version.ref = "ideaGradlePlugin" }
kotlinJs = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
