name: CI checks

on:
  push:
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run :assemble task
      run: ./gradlew assemble

  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run :check task
        run: ./gradlew check
      - name: Merge SARIF files into one
        uses: jduimovich/collect-sarif-files@main
        with:
          input-file-name: ${{ github.workspace }}/build/*.sarif
          output-file-name: ${{ github.workspace }}/build/static-analysis.sarif

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/build/static-analysis.sarif
          checkout_path: ${{ github.workspace }}

  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.4
